### ISSUE TITLE
Implement features for release1

### ISSUE THREAD

**Issue by reswanson** [reswanson/csc422-group2#5]
Features for Release1

How do we want to split this stories?

each survivor attacks each zombie
then each zombie attacks each survivor
-----------
random arrays of 5-20 survivors and zombie of each type.
list: n .. (z z z)
     n    s s s

each s attacks each z, 
each z attacks each s
repeat
----------
zombie
generate random  number between 5 -20   number of zombies
loop thru those, and generate random 0-1 (switch for tank/common)

same for survivor 0-2 for each type  s t c
------

The program randomly generates an array of survivors and zombies. Make each survivor attack 
every zombie. Next, make each zombie attack every survivor. Repeat until all zombie or all
survivors are dead. Then print a report of how many survivors made it to safety. A dead survivor
or a dead zombie should not attack. Your team have the freedom to design it anyway you like.
You will definitely find what you learn in Object Oriented programming to be very useful

---
Release 1.0's sample run:

We have 17 survivors trying to make it to safety.
But there are 8 zombies waiting for them.
It seems 6 have made it to safety.

**Comment by bschugel1** [comment]
Release v1.0 released
